Ported our Genetic Algorithm library to v2.0.0
comprobo-final-project/comprobo_final_project pull request #24
Opened 2017-04-29 14:51 UTC by hdavidzhu

- Used numpy
- Collapsed a lot of different nestings of classes
- Simplified, no more Supervisor, Chromosome, Population
- Plug and play fitness function
- Genetic algorithm less dependent on robots

2017-04-29 20:56 UTC, PrimePalaver requested changes

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +                        buf.append(self._mutate(child))
In the `_functionName()` notation, what does the underscore mean?

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        # Create rest of chromsosomes with crossovers and mutations
Change chromosomes to organisms

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        other: second organism to crossover
Docstring is out of date

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        _organism = organism[:]
What does the underscore mean on a variable name?

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        _organism[index_to_mutate] = np.clip(_organism[index_to_mutate],
Is it fine that we only clip the mutated index?

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        self._organisms = np.asarray(buf)
Does this actually sort like the comment says?

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        return self._organisms[choices][choice]
Can you add comments about the specifics of what is happening here? Choose 5 random organisms and pick the most fit of those 5? What if the generation size is less than 5?

2017-04-29 20:56 UTC, PrimePalaver commented on comprobo_final_project/scripts/gene_alg_2/genetic_algorithm.py
> +    def train(self):
Docstrings?

2017-04-29 20:56 UTC, shanek21 commented on comprobo_final_project/scripts/robot_controller.py
> +    genes = [2.77160000e+01, 7.72100000e+00, 7.61100000e+00, 8.00000000e-03]
What's with the scientific notation?

2017-04-29 20:56 UTC, shanek21 commented on comprobo_final_project/scripts/tasks/goal_task.py
> +        return _fitness_func
Is this a function defined within a method? Is that a thing?

2017-04-29 21:26 UTC, hdavidzhu commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +                        buf.append(self._mutate(child))
private method

2017-04-29 21:27 UTC, hdavidzhu commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        other: second organism to crossover
that's why self documenting code ftw ayyyeee

2017-04-29 21:27 UTC, hdavidzhu commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        _organism = organism[:]
All _ mean private. meaning another class should not be using those variables

2017-04-29 21:28 UTC, hdavidzhu commented on comprobo_final_project/scripts/robot_controller.py
> +    genes = [2.77160000e+01, 7.72100000e+00, 7.61100000e+00, 8.00000000e-03]
numpy ¯\_(ツ)_/¯

2017-04-29 21:29 UTC, hdavidzhu commented on comprobo_final_project/scripts/tasks/goal_task.py
> +        return _fitness_func
yep, you define a function, and then return it. This creates a closure, which allows that function to having a binding to our `robot`. This way, we don't have to pass our `robot` into the GeneticAlgorithm, which would be wrong.

2017-04-30 01:53 UTC, hdavidzhu commented on comprobo_final_project/scripts/gene_alg_2/generation.py
> +        _organism[index_to_mutate] = np.clip(_organism[index_to_mutate],
Yes? I didn't really write that code, also it would only go over during a mutate, so I would assume so.

2017-05-01 23:09 UTC, PrimePalaver approved these changes

2017-05-02 00:05 UTC, merged